services:
  - type: web
    name: fastapi-mediapipe
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildCommand: ""
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
